from datetime import date, datetime
from pydantic import BaseModel, ConfigDict
from enum import Enum
from typing import Optional

# Enums act as methods to define data validation for the fields in the Work_Load model. 
# They ensure that only specific values can be assigned to those fields.
# This helps maintain data integrity and consistency in the application.

class AcademicYear(Enum):
    AY_2025_2026 = "2025/2026"
    AY_2026_2027 = "2026/2027"
    AY_2027_2028 = "2027/2028"
    AY_2028_2029 = "2028/2029"
    AY_2029_2030 = "2029/2030"

class TermOrSemester(Enum):
    Semester_1 = "Semester 1"
    Semester_2 = "Semester 2"

class StudyType(Enum):
    written_report = "Written Report"
    presentation = "Presentation"
    pilot_study = "Pilot Study"
    academic_poster = "Academic Poster"
    academic_paper = "Academic Paper"
    thesis = "Thesis"


# The WorkLoadCreate model is used for creating new work load entries
# The WorkLoad model includes additional fields for the unique identifier and timestamps, these are generated by the database when a new entry is created.

class WorkLoadCreate(BaseModel):
    module_name: str
    academic_year: AcademicYear
    term_or_semester: TermOrSemester
    study_type: StudyType
    start_date: date
    end_date: date
    chart_colour: str
    notes: Optional[str] = None


class WorkLoad(WorkLoadCreate): # pythonic method of passing all the fields from WorkLoadCreate to WorkLoad, and then adding the additional fields specific to WorkLoad
    model_config = ConfigDict(from_attributes=True) # allows the model to be created from a dictionary of attributes, useful when receiving data from the frontend or database
    id: int
    created_at: datetime
    updated_at: Optional[datetime] = None

'''
WorkLoad(
    module_name = "Example Module",
    academic_year = AcademicYear.AY_2025_2026,
    term_or_semester = TermOrSemester.Semester_1,
    study_type = StudyType.written_report,
    start_date = date(2025, 9, 1),
    end_date = date(2025, 12, 15),
    chart_colour = "#FF5733",
    notes = "This is an example work load entry.",
)
'''
